require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.osc52")
require("user.notify")
require("user.keymaps")
require("user.fzf-lua")
require("user.autopairs")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.autocommands")

-- Deferred past the first redraw: none of these need to be ready before the
-- session's buffers appear, and they're the heaviest chunk of startup.
vim.schedule(function()
	require("user.cmp")
	require("user.lsp")
	require("user.snippets")
end)
